# Generated by Django 5.2.1 on 2025-06-09 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Haus & Garten > Dekoration', max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('contact_name', models.CharField(default='Axel', max_length=100)),
                ('contact_phone', models.CharField(default='15563056052', max_length=20)),
                ('contact_zipcode', models.CharField(default='80331', max_length=20)),
                ('content_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('is_posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='furniture_images/')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketplace.furniture')),
            ],
        ),
    ]
