# Generated by Django 5.2.1 on 2025-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
